version: '3.8'
services:
  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./react/node_modules:/app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - MONGO_DB_URI=mongodb://mongo:27017/test_db
    volumes:
      - ./backend/node_modules:/usr/src/app/node_modules
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
